FROM centos:7

# Install Java.
RUN \
    yum -y install wget \
    && mkdir -p /opt/java/ && cd /opt/java/ \
    && wget --no-cookies --no-check-certificate \
    --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
    "http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz"\
    && tar xzf jdk-8u181-linux-x64.tar.gz \
    && rm -f jdk-8u181-linux-x64.tar.gz

# Define working directory.
RUN \
    mkdir -p /home/app/ \
    && yum -y install kde-l10n-Chinese \
    && yum -y reinstall glibc-common \
    && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8

# Define commonly used JAVA_HOME variable

ENV LC_ALL zh_CN.utf8

ENV JAVA_HOME /opt/java/jdk1.8.0_181
ENV APP_HOME /home/app/
ENV PATH ${JAVA_HOME}/bin:${PATH}

WORKDIR ${APP_HOME}

# Define default command.
ENTRYPOINT ["java", "-version"]
